apiVersion: v1
kind: ConfigMap
metadata:
  name: gpushare-scheduler-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "extenders" : [{
      "urlPrefix": "http://127.0.0.1:12345/gpushare-scheduler",
      "filterVerb": "filter",
      "bindVerb": "bind",
      "weight": 9,
      "enableHttps": false,
      "nodeCacheCapable": true
    }]
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpushare-scheduler
  namespace: kube-system
  labels:
    app: gpushare-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpushare-scheduler
  template:
    metadata:
      labels:
        app: gpushare-scheduler
    spec:
      volumes:
      - name: gpushare-scheduler-config
        configMap:
          name: gpushare-scheduler-policy
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes
      - name: caconfig
        hostPath:
          path: /opt/k8s/node
      containers:
      - name: gpushare-scheduler-ctr
        image: googlecontainersmirrors/hyperkube-amd64:v1.9.3
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --logtostderr=true
        - --master=http://10.25.85.43:8080
        - --address=0.0.0.0
        - --leader-elect=false
        - --scheduler-name=gpushare-scheduler
        - --port=10251
        - --use-legacy-policy-config=true
        - --policy-config-file=/my-scheduler/policy.cfg
        - -v=4
        volumeMounts:
        - name: gpushare-scheduler-config
          mountPath: /my-scheduler
      - name: gpushare-scheduler-extender-ctr
        image: a/b:c
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: debug
        - name: PORT
          value: "12345"
        - name: TZ
          value: "Asia/Shanghai"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: kubeconfig
          - mountPath: /opt/k8s/node
            name: caconfig
#        livenessProbe:
#          httpGet:
#            path: /version
#            port: 12345
#        readinessProbe:
#          httpGet:
#            path: /version
#            port: 12345
        ports:
          - containerPort: 12345
